version: '3.8'

services:
  api01: &api
    build: .
    hostname: api01
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=rinha
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - PORT=8080
    ports:
      - "8081:8080"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 150M

  api02:
    <<: *api
    hostname: api02
    ports:
      - "8082:8080"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 50M

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 350M
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c synchronous_commit=off

volumes:
  postgres_data:

networks:
  default:
    driver: bridge
    name: rinha-backend-network
